source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"

use_frameworks!

target "imoji-kit" do
	pod 'ImojiSDKUI/CollectionView', :path => '../../'
	pod 'ImojiSDKUI/Editor', :path => '../../'
end
