source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

target "artmoji" do
    pod 'ImojiSDKUI/CollectionView'
    pod 'ImojiSDKUI/Editor'
end

target "artmoji-photos" do
    pod 'ImojiSDKUI/CollectionView'
    pod 'ImojiSDKUI/Editor'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == 'ImojiSDKUI'
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'IMOJI_APP_EXTENSION=1']
            end
        end
    end
end
